export const PICTURE_TRIVIA_QUESTIONS = [
  {
    id: "pic-1",
    category_es: "Geografía & Maravillas",
    category_en: "Geography & Wonders",
    categoryIcon: "🗼",
    question_es: "¿En qué famosa capital del mundo se encuentra esta colosal torre de hierro?",
    question_en: "In which famous world capital is this colossal iron tower located?",
    imageEmoji: "🗼",
    imageTitle_es: "Torre Eiffel · 330m de altura",
    imageTitle_en: "Eiffel Tower · 330m tall",
    options_es: ["Roma", "París", "Berlín", "Londres"],
    options_en: ["Rome", "Paris", "Berlin", "London"],
    answerIndex: 1,
    fact_es: "Fue construida para la Exposición Universal de París de 1889 por Gustave Eiffel.",
    fact_en: "Built for the 1889 Paris Universal Exposition by engineer Gustave Eiffel.",
    points: 120
  },
  {
    id: "pic-2",
    category_es: "Cine & Animación",
    category_en: "Animation & Film",
    categoryIcon: "🦁",
    question_es: "¿Qué clásico de Disney nos mostró por primera vez la icónica 'Roca del Rey'?",
    question_en: "Which Disney classic first featured the iconic 'Pride Rock'?",
    imageEmoji: "👑🦁🌅",
    imageTitle_es: "El Reino Animal en la Sabana",
    imageTitle_en: "Animal Kingdom in the Savanna",
    options_es: ["Madagascar", "Tarzán", "El Rey León", "El Libro de la Selva"],
    options_en: ["Madagascar", "Tarzan", "The Lion King", "The Jungle Book"],
    answerIndex: 2,
    fact_es: "El Rey León (1994) es una de las películas animadas tradicionales más exitosas de la historia.",
    fact_en: "The Lion King (1994) is one of the highest-grossing hand-drawn animated films in history.",
    points: 120
  },
  {
    id: "pic-3",
    category_es: "Arte & Pintura",
    category_en: "Art & Masterpieces",
    categoryIcon: "🎨",
    question_es: "¿Qué genial pintor holandés pintó la célebre obra 'La Noche Estrellada'?",
    question_en: "Which brilliant Dutch artist painted the famous masterpiece 'The Starry Night'?",
    imageEmoji: "🌌✨🎨",
    imageTitle_es: "Cielo Arremolinado y Ciprés",
    imageTitle_en: "Swirling Sky & Cypress",
    options_es: ["Pablo Picasso", "Vincent van Gogh", "Claude Monet", "Salvador Dalí"],
    options_en: ["Pablo Picasso", "Vincent van Gogh", "Claude Monet", "Salvador Dalí"],
    answerIndex: 1,
    fact_es: "Van Gogh la pintó en junio de 1889 desde su ventana en Saint-Rémy-de-Provence.",
    fact_en: "Van Gogh painted it in June 1889 from his window in Saint-Rémy-de-Provence.",
    points: 150
  },
  {
    id: "pic-4",
    category_es: "Música & Leyendas",
    category_en: "Music & Legends",
    categoryIcon: "🎸",
    question_es: "¿Qué legendario cuarteto británico cruzó el paso peatonal de 'Abbey Road'?",
    question_en: "Which legendary British band walked across the famous 'Abbey Road' crosswalk?",
    imageEmoji: "🚶‍♂️🚶‍♂️🚶‍♂️🚶‍♂️ zebra",
    imageTitle_es: "Paso de Cebra más Famoso del Mundo",
    imageTitle_en: "World's Most Famous Crosswalk",
    options_es: ["Queen", "The Rolling Stones", "The Beatles", "Pink Floyd"],
    options_en: ["Queen", "The Rolling Stones", "The Beatles", "Pink Floyd"],
    answerIndex: 2,
    fact_es: "La fotografía de la portada del álbum Abbey Road fue tomada el 8 de agosto de 1969.",
    fact_en: "The cover photograph for Abbey Road was captured on August 8, 1969.",
    points: 120
  },
  {
    id: "pic-5",
    category_es: "Exploración Espacial",
    category_en: "Space Exploration",
    categoryIcon: "🚀",
    question_es: "¿En qué año alunizó por primera vez el ser humano en la misión Apolo 11?",
    question_en: "In what year did humans first set foot on the Moon during Apollo 11?",
    imageEmoji: "🌕👨‍🚀🚀",
    imageTitle_es: "'Un pequeño paso para el hombre...'",
    imageTitle_en: "'One small step for man...'",
    options_es: ["1965", "1969", "1972", "1975"],
    options_en: ["1965", "1969", "1972", "1975"],
    answerIndex: 1,
    fact_es: "Neil Armstrong y Buzz Aldrin caminaron en la Luna el 20 de julio de 1969.",
    fact_en: "Neil Armstrong and Buzz Aldrin walked on the Moon on July 20, 1969.",
    points: 130
  }
];
