export const PICTURE_TRIVIA_QUESTIONS = [
  {
    id: "pic-1",
    category_es: "Geografía & Maravillas",
    category_en: "Geography & Wonders",
    categoryIcon: "🗼",
    question_es: "¿En qué famosa capital del mundo se encuentra esta colosal torre de hierro?",
    question_en: "In which famous world capital is this colossal iron tower located?",
    imageUrl: "assets/images/trivia/eiffel_tower.webp",
    imageAlt: "Torre Eiffel, París",
    imageTitle_es: "Torre Eiffel · 330m de Altura",
    imageTitle_en: "Eiffel Tower · 330m Tall",
    options_es: ["Roma", "París", "Berlín", "Londres"],
    options_en: ["Rome", "Paris", "Berlin", "London"],
    answerIndex: 1,
    fact_es: "Fue construida para la Exposición Universal de París de 1889 por el ingeniero Gustave Eiffel.",
    fact_en: "Built for the 1889 Paris Universal Exposition by engineer Gustave Eiffel.",
    points: 120
  },
  {
    id: "pic-2",
    category_es: "Cine & Animación",
    category_en: "Animation & Film",
    categoryIcon: "🦁",
    question_es: "¿Qué clásico de Disney nos mostró por primera vez la icónica 'Roca del Rey'?",
    question_en: "Which Disney classic first featured the iconic 'Pride Rock'?",
    imageUrl: "assets/images/trivia/pride_rock_lion.webp",
    imageAlt: "León en la Sabana Africana",
    imageTitle_es: "El Reino Animal en la Sabana",
    imageTitle_en: "Animal Kingdom in the Savanna",
    options_es: ["Madagascar", "Tarzán", "El Rey León", "El Libro de la Selva"],
    options_en: ["Madagascar", "Tarzan", "The Lion King", "The Jungle Book"],
    answerIndex: 2,
    fact_es: "El Rey León (1994) es una de las películas animadas tradicionales más exitosas y aclamadas de la historia.",
    fact_en: "The Lion King (1994) is one of the highest-grossing hand-drawn animated films in cinema history.",
    points: 120
  },
  {
    id: "pic-3",
    category_es: "Arte & Pintura",
    category_en: "Art & Masterpieces",
    categoryIcon: "🎨",
    question_es: "¿Qué genial pintor holandés pintó la célebre obra 'La Noche Estrellada'?",
    question_en: "Which brilliant Dutch artist painted the famous masterpiece 'The Starry Night'?",
    imageUrl: "assets/images/trivia/starry_night.webp",
    imageAlt: "La Noche Estrellada de Vincent van Gogh",
    imageTitle_es: "Cielo Arremolinado y Ciprés",
    imageTitle_en: "Swirling Sky & Cypress",
    options_es: ["Pablo Picasso", "Vincent van Gogh", "Claude Monet", "Salvador Dalí"],
    options_en: ["Pablo Picasso", "Vincent van Gogh", "Claude Monet", "Salvador Dalí"],
    answerIndex: 1,
    fact_es: "Van Gogh la pintó en junio de 1889 desde su ventana en Saint-Rémy-de-Provence.",
    fact_en: "Van Gogh painted it in June 1889 from his window in Saint-Rémy-de-Provence.",
    points: 150
  },
  {
    id: "pic-4",
    category_es: "Música & Leyendas",
    category_en: "Music & Legends",
    categoryIcon: "🎸",
    question_es: "¿Qué legendario cuarteto británico cruzó el paso peatonal de 'Abbey Road'?",
    question_en: "Which legendary British band walked across the famous 'Abbey Road' crosswalk?",
    imageUrl: "assets/images/trivia/abbey_road.webp",
    imageAlt: "Paso Peatonal de Abbey Road en Londres",
    imageTitle_es: "Paso de Cebra más Famoso del Mundo",
    imageTitle_en: "World's Most Famous Crosswalk",
    options_es: ["Queen", "The Rolling Stones", "The Beatles", "Pink Floyd"],
    options_en: ["Queen", "The Rolling Stones", "The Beatles", "Pink Floyd"],
    answerIndex: 2,
    fact_es: "La fotografía de la portada del álbum Abbey Road fue tomada el 8 de agosto de 1969 en Londres.",
    fact_en: "The cover photograph for Abbey Road was captured on August 8, 1969 in London.",
    points: 120
  },
  {
    id: "pic-5",
    category_es: "Exploración Espacial",
    category_en: "Space Exploration",
    categoryIcon: "🚀",
    question_es: "¿En qué año alunizó por primera vez el ser humano en la misión Apolo 11?",
    question_en: "In what year did humans first set foot on the Moon during Apollo 11?",
    imageUrl: "assets/images/trivia/apollo11_moon.webp",
    imageAlt: "Alunizaje Apolo 11 en la Luna",
    imageTitle_es: "'Un pequeño paso para el hombre...'",
    imageTitle_en: "'One small step for man...'",
    options_es: ["1965", "1969", "1972", "1975"],
    options_en: ["1965", "1969", "1972", "1975"],
    answerIndex: 1,
    fact_es: "Neil Armstrong y Buzz Aldrin caminaron sobre el Mar de la Tranquilidad lunar el 20 de julio de 1969.",
    fact_en: "Neil Armstrong and Buzz Aldrin walked on the Moon's Sea of Tranquility on July 20, 1969.",
    points: 130
  },
  {
    id: "pic-6",
    category_es: "Arqueología & Historia",
    category_en: "Archaeology & History",
    categoryIcon: "⛰️",
    question_es: "¿En qué país de Sudamérica se ubica la imponente ciudadela inca de Machu Picchu?",
    question_en: "In which South American country is the breathtaking Inca citadel of Machu Picchu located?",
    imageUrl: "assets/images/trivia/machu_picchu.webp",
    imageAlt: "Machu Picchu, Perú",
    imageTitle_es: "Ciudadela Inca en los Andes",
    imageTitle_en: "Inca Citadel in the Andes",
    options_es: ["Bolivia", "Perú", "Ecuador", "Chile"],
    options_en: ["Bolivia", "Peru", "Ecuador", "Chile"],
    answerIndex: 1,
    fact_es: "Machu Picchu fue edificada en el siglo XV a más de 2,430 metros de altitud en la cordillera de los Andes.",
    fact_en: "Machu Picchu was built in the 15th century over 2,430 meters above sea level in the Andes mountains.",
    points: 140
  },
  {
    id: "pic-7",
    category_es: "Imperios de la Antigüedad",
    category_en: "Ancient Empires",
    categoryIcon: "🏛️",
    question_es: "¿Cómo se llama este monumental anfiteatro romano inaugurado en el año 80 d.C.?",
    question_en: "What is the name of this monumental Roman amphitheater inaugurated in 80 AD?",
    imageUrl: "assets/images/trivia/colosseum_rome.webp",
    imageAlt: "Coliseo Romano, Roma",
    imageTitle_es: "Anfiteatro Flavio · Roma",
    imageTitle_en: "Flavian Amphitheatre · Rome",
    options_es: ["Panteón de Agripa", "Coliseo Romano", "Circo Máximo", "Foro Imperial"],
    options_en: ["Pantheon", "Roman Colosseum", "Circus Maximus", "Imperial Forum"],
    answerIndex: 1,
    fact_es: "El Coliseo de Roma podía albergar a más de 50,000 espectadores para luchas de gladiadores y espectáculos públicos.",
    fact_en: "The Roman Colosseum could accommodate over 50,000 spectators for gladiatorial contests and public spectacles.",
    points: 130
  },
  {
    id: "pic-8",
    category_es: "Arquitectura & Amor",
    category_en: "Architecture & Wonders",
    categoryIcon: "🕌",
    question_es: "¿En qué país asiático se levanta el majestuoso mausoleo de mármol blanco Taj Mahal?",
    question_en: "In which Asian country stands the majestic white marble mausoleum Taj Mahal?",
    imageUrl: "assets/images/trivia/taj_mahal.webp",
    imageAlt: "Taj Mahal, Agra, India",
    imageTitle_es: "Joya de Mármol en Agra",
    imageTitle_en: "Marble Jewel in Agra",
    options_es: ["Pakistán", "India", "Turquía", "Egipto"],
    options_en: ["Pakistan", "India", "Turkey", "Egypt"],
    answerIndex: 1,
    fact_es: "Fue construido entre 1631 y 1648 por el emperador mogol Shah Jahan en memoria de su esposa favorita Mumtaz Mahal.",
    fact_en: "Built between 1631 and 1648 by Mughal emperor Shah Jahan in memory of his favorite wife Mumtaz Mahal.",
    points: 130
  }
];
