export const SPONSORED_ADS = [
  {
    id: "ad-video-1",
    brand: "AUTOBOTEC.NET · MEDIA NETWORK",
    badge: "¡ANUNCIA TU NEGOCIO AQUÍ!",
    badge_en: "ADVERTISE YOUR BUSINESS HERE!",
    headline: "¡ANUNCIA TU NEGOCIO AQUÍ! · AUTOBOTEC.NET",
    headline_en: "ADVERTISE YOUR BUSINESS HERE! · AUTOBOTEC.NET",
    subtext: "Llega a más de 3,000+ pasajeros cautivos cada mes en Uber y Lyft con pantallas interactivas de alta conversión. Escanea el código QR para tarifas y contratación inmediata.",
    subtext_en: "Reach over 3,000+ captive passengers every month on Uber & Lyft with high-converting interactive screens. Scan the QR code to hire ads.",
    videoUrl: "assets/videos/video_autobotec_1789922115206.mp4",
    qrCodeText: "https://autobotec.net",
    promoCode: "AUTOBOTEC26",
    theme: "amber",
    gradient: "linear-gradient(135deg, #0a0f1d 0%, #1e1b4b 50%, #312e81 100%)",
    accentColor: "#f8b800",
    icon: "🚀",
    duration: 15
  },
  {
    id: "ad-1",
    brand: "VELOCE ESPRESSO & BAKERY",
    badge: "Oferta Local en tu Ruta",
    headline: "¡Tu café artesanal favorito te espera en la próxima esquina!",
    subtext: "Muestra tu viaje en Uber/Lyft y obtén 30% OFF en tu primer café de especialidad + croissant gratis.",
    videoUrl: "assets/videos/anuncia_aqui_autobotec.mp4",
    qrCodeText: "https://copilot.promo/veloce-coffee",
    promoCode: "COPILOT30",
    theme: "amber",
    gradient: "linear-gradient(135deg, #1c1308 0%, #2e1d09 50%, #452405 100%)",
    accentColor: "#f59e0b",
    icon: "☕",
    duration: 10
  },
  {
    id: "ad-2",
    brand: "NEXUS FIT GYMS 24/7",
    badge: "Patrocinador Premium",
    headline: "Entrena sin límites en más de 50 clubes de la ciudad",
    subtext: "Pase VIP ilimitado por 7 días sin costo para pasajeros de Copilot Driver. Escanea y activa tu membresía.",
    videoUrl: "assets/videos/anuncia_aqui_autobotec.mp4",
    qrCodeText: "https://copilot.promo/nexus-pass",
    promoCode: "COPILOTVIP",
    theme: "cyan",
    gradient: "linear-gradient(135deg, #041b24 0%, #063142 50%, #084c66 100%)",
    accentColor: "#06b6d4",
    icon: "⚡",
    duration: 10
  },
  {
    id: "ad-3",
    brand: "STREAMWAVE CINEMA",
    badge: "Estreno de la Semana",
    headline: "Mira películas y series de estreno directo en tu móvil",
    subtext: "Disfruta 1 mes gratis de streaming 4K sin anuncios para disfrutar en cualquier trayecto.",
    videoUrl: "assets/videos/anuncia_aqui_autobotec.mp4",
    qrCodeText: "https://copilot.promo/streamwave-free",
    promoCode: "RIDEFREE",
    theme: "purple",
    gradient: "linear-gradient(135deg, #1a0b2e 0%, #2f1354 50%, #4c1d95 100%)",
    accentColor: "#a855f7",
    icon: "🎬",
    duration: 10
  },
  {
    id: "ad-4",
    brand: "PRIME BURGER HOUSE",
    badge: "Cena Recomendada",
    headline: "Hamburguesas ahumadas con ingredientes 100% orgánicos",
    subtext: "Pide por la app antes de llegar a tu destino con envío gratis usando el código del copiloto.",
    videoUrl: "assets/videos/anuncia_aqui_autobotec.mp4",
    qrCodeText: "https://copilot.promo/prime-burger",
    promoCode: "RIDERBURGER",
    theme: "rose",
    gradient: "linear-gradient(135deg, #2b0c16 0%, #4a1224 50%, #881337 100%)",
    accentColor: "#f43f5e",
    icon: "🍔",
    duration: 10
  }
];
